# Generated by Django 2.0.9 on 2018-10-16 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0004_auto_20181016_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagIndexPage',
            new_name='BlogTagIndex',
        ),
    ]
